/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacyinventorymangementsystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Tan
 */
public class UserSearch extends javax.swing.JFrame {

     Vector<String> M_CN = new Vector<String>();
	Vector<String> M_N = new Vector<String>();
	Vector<String> M_Q = new Vector<String>();
	Vector<String> M_SP = new Vector<String>();
	Vector<String> M_TP = new Vector<String>(); 
	
	String typed = new String();// To store string typed by User/Admin
	String temp = new String();
	int count = 0;
        static int Q = 0;
        
    public UserSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MCNtxt = new javax.swing.JTextField();
        MNtxt = new javax.swing.JTextField();
        MQtxt = new javax.swing.JTextField();
        MSPtxt = new javax.swing.JTextField();
        MTPtxt = new javax.swing.JTextField();
        SearchMButton = new javax.swing.JButton();
        SearchBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel6.setText("Search Medicine Data");

        jLabel1.setText("Medicine Code Number :");

        jLabel2.setText("Medicine Name:");

        jLabel3.setText("Quantity(Units) :");

        jLabel4.setText("Price in Single Unit :");

        jLabel5.setText("Total Price :");

        MCNtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCNtxtActionPerformed(evt);
            }
        });

        SearchMButton.setText("Search");
        SearchMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMButtonActionPerformed(evt);
            }
        });

        SearchBackButton.setText("BACK");
        SearchBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MCNtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(MNtxt)
                            .addComponent(MQtxt)
                            .addComponent(MSPtxt)
                            .addComponent(MTPtxt))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(SearchMButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MCNtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MNtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MQtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MSPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MTPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchMButton)
                    .addComponent(SearchBackButton))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MCNtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCNtxtActionPerformed

    }//GEN-LAST:event_MCNtxtActionPerformed

    private void SearchMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMButtonActionPerformed
        LoadPreviousData();
        SearchMedicineData();
    }//GEN-LAST:event_SearchMButtonActionPerformed

    private void SearchBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBackButtonActionPerformed
        new UserGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SearchBackButtonActionPerformed

   public void LoadPreviousData(){
        try{
            FileReader inputFile = new FileReader ("Text.txt");
            BufferedReader bufferR = new BufferedReader (inputFile);

            typed = bufferR.readLine();


            for (int i =0 ; i < typed.length() ; i ++){
                if(typed.charAt(i) =='|'){
                    count = count + 1;
                }

                else if(typed.charAt(i) =='/'){
                    M_CN.addElement(temp);
                    temp = "";
                }
                else{
                    temp = temp + typed.charAt(i);
                }
            }
            typed = bufferR.readLine();

            for (int i =0 ; i <typed.length() ; i ++){
                if(typed.charAt(i)=='|'){
                    count = count + 1;
                }

                else if(typed.charAt(i)=='/'){
                    M_N.addElement(temp);
                    temp = "";
                }

                else{
                    temp = temp + typed.charAt(i);
                }
            }
            typed = bufferR.readLine();

            for (int i =0 ; i <typed.length() ; i ++){
                if(typed.charAt(i)=='|'){
                    count = count + 1;
                }

                else if(typed.charAt(i)=='/'){
                    M_Q.addElement(temp);
                    temp = "";
                }

                else{
                    temp = temp + typed.charAt(i);
                }
            }
            typed = bufferR.readLine();

            for (int i =0 ; i <typed.length() ; i ++){
                if(typed.charAt(i)=='|'){
                    count = count + 1;
                }

                else if(typed.charAt(i)=='/'){
                    M_SP.addElement(temp);
                    temp = "";
                }

                else{
                    temp = temp + typed.charAt(i);
                }
            }
            typed = bufferR.readLine();

            for (int i =0 ; i <typed.length() ; i ++){
                if(typed.charAt(i)=='|'){
                    count = count + 1;
                }

                else if(typed.charAt(i)=='/'){
                    M_TP.addElement(temp);
                    temp = "";
                }

                else{
                    temp = temp + typed.charAt(i);
                }
            }

            //JOptionPane.showMessageDialog(null,"File Retrieval Successful!!");
            bufferR.close();

        }

        catch(IOException e){
            //JOptionPane.showMessageDialog(null,"Error");
        }
    }
    
    
    
    
    public void SearchMedicineData(){//The search box

        String search;
        int j = 0;
        boolean found = false;

        search = JOptionPane.showInputDialog("Please Enter an ID");

        for(int i = 0;i < M_CN.size(); i++)
        {
            if(M_CN.elementAt(i).equals(search)){
                found = true;
                j = i;
                break;
            }
        }
        if(found == true){

            MCNtxt.setText(M_CN.elementAt(j));
            MNtxt.setText(M_N.elementAt(j));
            MQtxt.setText(M_Q.elementAt(j));
            MSPtxt.setText(M_SP.elementAt(j));
            MTPtxt.setText(M_TP.elementAt(j));
        }
        else{
            JOptionPane.showMessageDialog(null,"To Search, enter a User ID","Search Data", JOptionPane.QUESTION_MESSAGE);
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MCNtxt;
    private javax.swing.JTextField MNtxt;
    private javax.swing.JTextField MQtxt;
    private javax.swing.JTextField MSPtxt;
    private javax.swing.JTextField MTPtxt;
    private javax.swing.JButton SearchBackButton;
    private javax.swing.JButton SearchMButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
